name: CI

on:
  push:
    branches: "*"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installing norminette
        run: python3 -m pip install norminette
        
      - name: Running norminette
        run: norminette src include libs/libft

      - name: Installing MLX42 dependencies
        run: sudo apt install build-essential libx11-dev libglfw3-dev libglfw3 xorg-dev

      - name: Compiling binary
        run: make
